name: Deploy Hugo site to Public Repo

on:
  push:
    branches: ["main"]
  workflow_dispatch:  # allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

env:
  HUGO_ENV: production
  HUGO_VERSION: "0.151.0"
  GO_VERSION: "1.23.3"
  TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
  TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
  TINA_SEARCH_TOKEN: ${{ secrets.TINA_SEARCH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # -----------------------------
      # Cache Hugo
      - name: Cache Hugo
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/hugo
          key: hugo-${{ env.HUGO_VERSION }}

      - name: Install Hugo
        if: steps.cache-hugo.outputs.cache-hit != 'true'
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      # -----------------------------
      # Cache Go
      - name: Cache Go
        uses: actions/cache@v3
        with:
          path: /usr/local/go
          key: go-${{ env.GO_VERSION }}

      - name: Install Go
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: |
          wget -O ${{ runner.temp }}/go.tar.gz https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf ${{ runner.temp }}/go.tar.gz

      # -----------------------------
      # Cache npm dependencies
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Setup Project
        run: npm run project-setup

      - name: Install npm dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to public repo in same org with custom domain
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}           # Default token works for same-org repo
          external_repository: coldsteam-studio/coldsteam-studio         # Replace with your public repo
          publish_dir: ./public
          publish_branch: main                                   # Or "gh-pages"
          commit_message: "Deploy Hugo site: ${{ github.sha }}"
          cname: "www.coldsteam.studio"                               # Replace with your custom domain

